apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: envisalink-to-mqtt
  labels:
    app: nightwatcher
    tier: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: envisalink-to-mqtt
    spec:
      containers:
      - name: envisalink
        image: rjferguson21/envisalink-to-mqtt2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        envFrom:
        - configMapRef:
            name: envisalink-config
        env:
        - name: GET_HOSTS_FROM
          value: dns